language: php
php:
  - 5.6
  - 7.0
  - 7.1
branches:
  only:
    - master
cache:
  directories:
    - $HOME/.composer/cache
before_script:
  - composer install --prefer-dist
script:
  - composer test
